<?php 
header("content-type:text/html;charset=utf-8");
//定义框架目录
define("THINK_PATH","ThinkPHP/");
//定义前台路径和名称
define("APP_PATH","./index");
define("APP_NAME","app");
//加载框架入口文件
require(THINK_PATH."ThinkPHP.php");
//实例化
APP::run();
?>